### PR TITLE
docker-compose: Expose 5000-5099 for sernet to localhost

### PR DESCRIPTION
**Pull request by galak**
Signed-off-by: Kumar Gala <kumar.gala@linaro.org>

### CODE REVIEW

**Review by pfalcon — APPROVED** [review]
We might also consider why we use 5000 starting port, instead of "upstream" 7101 (though we'd need to patch it anyway, as we have >1 connection).

**Comment by pfalcon** [comment]
Merged, by I took freedom to edit commit to add a comment about that port range: https://github.com/Linaro/lite-lava-docker-compose/commit/c0d251fa3490d0755951a33be53fc2b5a9a4596a (based on rebase experience, it's helpful to have inline hints why upstream config was patched, I added a few such during the rebase). (You'll need to git pull --rebase).

**Comment by galak** [comment]
> Merged, by I took freedom to edit commit to add a comment about that port range: [c0d251f](https://github.com/Linaro/lite-lava-docker-compose/commit/c0d251fa3490d0755951a33be53fc2b5a9a4596a) (based on rebase experience, it's helpful to have inline hints why upstream config was patched, I added a few such during the rebase). (You'll need to git pull --rebase).

Sounds good.

**Comment by galak** [comment]
> We might also consider why we use 5000 starting port, instead of "upstream" 7101 (though we'd need to patch it anyway, as we have >1 connection).

I'm curious if there is a typo w/the upstream 7101 as the upstream ser2net.conf has 7001.  Asking StevenR about it since he made the change.

**Pull request closed without merging**
