### PR TITLE
.env: Upgrade to LAVA 2019.05.

### PR DESCRIPTION
**Pull request by pfalcon**

### CODE REVIEW

**Comment by galak** [comment]
Want to wait on this as there was a 2019.05post1 release, however there aren't yet docker images for it:

https://lists.lavasoftware.org/pipermail/lava-announce/2019-June/000086.html

**Comment by pfalcon** [comment]
I guess there should be 2019.06 release soon (though I'm not sure about their release schedule).

**Comment by galak** [comment]
Also we need to remove the `overlays/lava-server/etc/lava-server/dispatcher-config/device-types/frdm-k64f.jinja2` and `overlays/lava-dispatcher/usr/lib/python3/dist-packages/lava_dispatcher/actions/boot/pyocd.py` as those fixes are now in the 2019.05 release.

**Comment by galak** [comment]
> I guess there should be 2019.06 release soon (though I'm not sure about their release schedule).

I've poked the LAVA guys about getting a 2019.05post1 for docker.

**Comment by galak** [comment]
Closing this, as we'll do this when the 0.6 release comes out.

**Comment by galak** [comment]
Closed in favor of #23

**Pull request closed without merging**
