### PR TITLE
docker-compose.yaml: Allow to use docker inside lava-dispatcher.

### PR DESCRIPTION
**Pull request by pfalcon**
So we can use LAVA's docker support (run docker containers on dispatcher,
which in our setup itself runs on docker).

Signed-off-by: Paul Sokolovsky <paul.sokolovsky@linaro.org>

### CODE REVIEW

**Comment by pfalcon** [comment]
@edmooring: Please review.

**Comment by pfalcon** [comment]
So, the story here is that LAVA already supports booting Docker containers. Somehow, based on our meeting with Remi at SAN19, I thought that's plans for future, and only LXC is supported now. Indeed, LAVA docs trumpet LXC support all around, and docs on Docker support in dispatcher are sparse at best. I was able to "reverse engineer" how to boot a docker image however, and it's not that hard, as the included sample job shows.

Docker support should (hopefully) truly open new horizons for writing complex tests in sufficiently easy manner, as dealing with LXC inside LAVA Docker setup was quite cumbersome, as previous experience showed.

**Comment by pfalcon** [comment]
Ok, I hope there're no concerns (indeed, the only change this makes is exporting host's docker socket to downstream docker, that's is pretty pervasive, e.g. https://docs.docker.com/compose/compose-file/ shows that (search for "Example Compose file version 3" and expand it).

So, let me merge it, and proceed with further docker functionality investigation.

**Comment by edmooring** [comment]
This looks really good. I suspect I can run the Xilinx QEMU docker container 
with a little extra work to get the images into the right places.

**Pull request merged**
