### PR TITLE
example: Add job for multinode net ping testing.

### PR DESCRIPTION
**Pull request by pfalcon**
Multinode job which boots an frdm_k64f with a IP networking application
(dump_http_server used here), and docker virtual device, and pings
the frdm_k64f from the docker.

Signed-off-by: Paul Sokolovsky <paul.sokolovsky@linaro.org>

### CODE REVIEW

**Comment by pfalcon** [comment]
@agansari: FYI, this is the job I'm going to use to test your changes in https://github.com/zephyrproject-rtos/zephyr/pull/21269 (and yeah, sorry for the delay with it, I'm trying to make a good dogfeeding setup, so we break thru the issues of "how did you test that" and "how to reproduce that testing easily").

**Comment by agansari** [comment]
@pfalcon thank you for implementing it, we greatly need such a tool.

You can also use i.mx 1050 rt, i've added that board to lava some time ago, the only difference would be support for jlink boot method only.

**Comment by pfalcon** [comment]
@agansari:

> You can also use i.mx 1050 rt, i've added that board to lava some time ago, the only difference would be support for jlink boot method only.

That's definitely the idea, to apply all that across the board. It's all however yet in setting up stage, and I don't want to spread thin and play with different boards now. Instead, I want to set up good "vertical" system and make sure it works well with one board - frdm_k64f (and even that keep bringing enough surprises ;-) ).

Thanks for review! (Marking it as WIP, as it requires changes for latest Zephyr master.)

**Comment by pfalcon** [comment]
Ok, I generalized the job a bit, and would like to merge it now, to serve as a reference job to help with configuring test boards networking in the Cambrdige LAVA lab, which happens right now.

**Pull request merged**
